export interface INotebook {
  Product_Brand: string,
  Release: number,
  Screen_Size: string,
  RAM_Slots: number,
  Resolution: string,
  Touch_Screen: boolean,
  Touch_ID: boolean,
  Face_Unlock: boolean,
  HDMI: boolean,
  GPU_Brand: string,
  GPU_Model: string,
  'USB-C_Ports': number,
  'USB-C_Display': boolean,
  Thunderbolt_3: boolean,
  Thunderbolt_4: boolean,
  'USB-C_Charging': boolean,
  CPU_Brand: string,
  CPU_Model: string,
  Core_Count: number,
  RAM_Max: number,
  RAM_Capacity: number,
  RAM_Type: string,
  Ethernet: boolean,
  '3.5mm_Jack': boolean,
  Refresh_Rate: number,
  Keyboard_Type: string,
  Keyboard_Light: boolean,
  Keyboard_SoftButtons: boolean,
  UEFI: boolean,
  Sensor: boolean,
  Price: number,
  Product: string,
  id: number,
  [key: string]: any;
}
